services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: dev
      APP_DEBUG: '1'
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:stable
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge